name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        run: echo "Thank you for your pull request! We appreciate your contribution."
